name: Build/release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          export TAG_NAME=$(echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///')
          git tag $TAG_NAME
          git push origin $TAG_NAME

  release:
    needs: tag
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - if: matrix.os != 'windows-latest'
        run: echo "TAG_NAME=$(echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///')" >> $GITHUB_ENV

      - if: matrix.os == 'windows-latest'
        run: echo "TAG_NAME=$(echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///')" >> $env:GITHUB_ENV

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ format('refs/tags/{0}', env.TAG_NAME) }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: pnpm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: pnpm run build:win

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
